import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { Role, FormulaType } from '@prisma/client';

export class User {
  @ApiProperty({
    description: 'User Id, generated by uuid',
    nullable: false,
    required: true,
    type: 'string',
    example: '2313w49-0db7-4v79-aacc-52624343bf2t',
  })
  id: string;

  @ApiProperty({
    description: 'First name',
    nullable: false,
    required: true,
    type: 'string',
    example: 'John',
  })
  firstname: string;

  @ApiProperty({
    description: 'Last name',
    nullable: false,
    required: true,
    type: 'string',
    example: 'Sample',
  })
  lastname: string;

  @ApiProperty({
    description: 'Email',
    uniqueItems: true,
    nullable: false,
    required: true,
    type: 'string',
    example: 'youremail@example.com',
  })
  email: string;

  @ApiProperty({
    description: 'User Role (admin, user)',
    nullable: false,
    required: true,
    type: 'string',
    example: 'user',
  })
  role: Role;

  @ApiPropertyOptional({
    description: 'Phone number',
    nullable: true,
    type: 'string',
    example: '+33123456789',
  })
  phone?: string;

  @ApiPropertyOptional({
    description: 'Birth date',
    nullable: true,
    type: 'string',
    example: '1990-01-01T00:00:00.000Z',
  })
  birthDate?: Date;

  @ApiPropertyOptional({
    description: 'FFT License number',
    nullable: true,
    type: 'string',
    example: '1234567',
  })
  fftLicenseNumber?: string;

  @ApiPropertyOptional({
    description: 'Formula type',
    enum: FormulaType,
    nullable: true,
    example: 'FULL',
  })
  formula?: FormulaType;

  @ApiPropertyOptional({
    description: 'Privacy consent date',
    nullable: true,
    type: 'string',
    example: '2024-01-01T00:00:00.000Z',
  })
  privacyConsentAt?: Date;

  @ApiPropertyOptional({
    description: 'Photo consent date',
    nullable: true,
    type: 'string',
    example: '2024-01-01T00:00:00.000Z',
  })
  photoConsentAt?: Date;

  @ApiPropertyOptional({
    description: 'Marketing consent date',
    nullable: true,
    type: 'string',
    example: '2024-01-01T00:00:00.000Z',
  })
  marketingConsentAt?: Date;

  @ApiPropertyOptional({
    description: 'Email notifications enabled',
    nullable: false,
    type: 'boolean',
    example: true,
  })
  notifyEmail?: boolean;

  @ApiPropertyOptional({
    description: 'SMS notifications enabled',
    nullable: false,
    type: 'boolean',
    example: false,
  })
  notifySMS?: boolean;

  @ApiPropertyOptional({
    description: 'WhatsApp notifications enabled',
    nullable: false,
    type: 'boolean',
    example: false,
  })
  notifyWhatsApp?: boolean;

  @ApiProperty({
    description: 'Created At',
    nullable: true,
    required: false,
    type: 'string',
    example: '2022-01-01T00:00:00.000Z',
  })
  createdAt?: Date;

  @ApiProperty({
    description: 'Updated At',
    nullable: true,
    required: false,
    type: 'string',
    example: '2022-01-01T00:00:00.000Z',
  })
  updatedAt?: Date;
}
